### ISSUE TITLE
Add a option to switch between dark and light mode.

### ISSUE THREAD

**Issue by rashen33** [rashen33/sky-cast-v2#3]
![image](https://github.com/rashen33/sky-cast-v2/assets/128305496/c7c6ca66-e15a-4887-9daa-b3ec2f043f37)

**Comment by CodeStrate** [comment]
@rashen33 I'd like to work on this issue, kindly add the ```hacktoberfest``` label to it.

**Comment by rashen33** [comment]
Hey, @CodeStrate. I will assign you to work on this issue. Keep working on this.

**Comment by PatilIsha** [comment]
hey,I'd like to work on this issue, kindly add the hacktoberfest label to it.

**Comment by PatilIsha** [comment]
hey,i want to slove your issues please acccept the request @CodeStrate

**Comment by CodeStrate** [comment]
@rashen33 Kindly review the PR #5
